[platformio]
src_dir = .

[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino

; 240 MHz CPU frequency
board_build.f_cpu = 240000000L

; 8MB Flash and 8MB PSRAM (OPI)
board_upload.flash_size = 8MB
board_build.partitions = default_8MB.csv
board_build.arduino.memory_type = qio_opi

; Build flags to enable PSRAM and Native USB CDC
build_flags =
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ; TFT_eSPI Custom Setup
    -D USER_SETUP_LOADED=1
    -include include/TFT_Setup.h

build_src_filter =
    +<*>
    -<lib/>
    -<.pio/>
    -<.git/>

lib_deps =
    bodmer/TFT_eSPI @ ^2.5.31
    esp32-camera
    greiman/SdFat @ ^2.2.3